package com.bank.islamic.fatwaandrulingrepository;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Bean;

/**
 * BIAN Service Domain: Fatwa And Ruling Repository
 *
 * Business Area:      Shariah Governance and Compliance
 * Business Domain:    Shariah Governance
 * Functional Pattern: Catalog
 * Asset Type:         Shariah Ruling
 * Control Record:     Shariah Ruling Directory Entry
 *
 * Generated by the islamic-platform service generator (Phase 1 — shallow build).
 * Replace the in-memory store with real persistence and domain logic in Phase 2.
 */
@SpringBootApplication
public class Application {

    public static void main(String[] args) {
        SpringApplication.run(Application.class, args);
    }

    @Bean
    public OpenAPI openApi() {
        return new OpenAPI().info(new Info()
                .title("Fatwa And Ruling Repository — BIAN Semantic API")
                .description("Service Domain 'Fatwa And Ruling Repository' (Catalog pattern) "
                        + "operating on the 'Shariah Ruling Directory Entry' control record.")
                .version("0.1.0"));
    }
}
